sudo: false

before_install:
  - ln -s . yum_repo_server

cache:
  - apt
  - bundler

addons:
  apt:
    packages:
    - rpm

rvm:
  - 1.9.3

script:
  - curl -s https://raw.githubusercontent.com/visibilityspots/ci-scripts/master/travis/puppet-module.sh | bash -s yum_repo_server development

notifications:
  email:
    - travis@visibilityspots.com
